[%IF TEST4_VAR1 == 1 %]
  TEST 4 HAS PASSED PART 1
  [%IF TEST4_VAR2 == 1 %]
    TEST 4 HAS FAILED
  [%ELSEIF TEST4_VAR2 == 2 %]
    TEST 4 HAS PASSED PART 2
    [%IF TEST4_VAR3 == 1 %]
      TEST 4 HAS FAILED
    [%ELSEIF TEST4_VAR3 == 2 %]
      TEST 4 HAS FAILED
    [%ELSE%]
      TEST 4 HAS PASSED PART 3
    [%ENDIF%]
  [%ENDIF%]
[%ELSE%]
  TEST 4 HAS FAILED
[%ENDIF%]
