<?php

/*
+----------------------------------------------------------------------+
|This program is free software; you can redistribute it and/or modify  |
|it under the terms of the GNU General Public License as published by  |
|the Free Software Foundation; either version 2 of the License, or     |
|(at your option) any later version.                                   |
|                                                                      |
|This program is distributed in the hope that it will be useful,       |
|but WITHOUT ANY WARRANTY; without even the implied warranty of        |
|MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the          |
|GNU General Public License for more details.                          |
|                                                                      |
|You should have received a copy of the GNU General Public License     |
|along with this program; if not, write to the Free Software           |
|Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.             |
+----------------------------------------------------------------------+
|Authors: Markus Nix <mnix@docuverse.de>                               |
+----------------------------------------------------------------------+
*/


using( 'util.datetime.namedays.lib.Date_Namedays' );


/**
 * @package util_datetime_namedays_lib
 */
 
class Date_Namedays_pl extends Date_Namedays
{
	/**
	 * Array of Namedays
	 *
	 * @var    array
	 * @access private
	 */
	var $_namedays = array(
		"1" => array(
			"1"  => array( "Mas³awa", "Mieczys³awa", "Mieszka" ),
			"2"  => array( "Bazylego", "Makarego", "Narcyzy" ),
			"3"  => array( "Arlety", "Danuty", "Lucjana" ),
			"4"  => array( "Anieli", "El¿biety", "Tytusa" ),
			"5"  => array( "Edwarda", "Hanny", "Szymona" ),
			"6"  => array( "Kacpra", "Melchiora", "Baltazara" ),
			"7"  => array( "Juliana", "Lucjana", "Walentyny" ),
			"8"  => array( "Artura", "Rajmunda", "Seweryny" ),
			"9"  => array( "Adriana", "Alicji", "Teresy" ),
			"10" => array( "Ady", "Jana", "Wilhelma" ),
			"11" => array( "Feliksa", "Honoraty", "Marty" ),
			"12" => array( "Bernarda", "Czes³awy", "Grety" ),
			"13" => array( "Bogumi³a", "Bogumi³y", "Weroniki" ),
			"14" => array( "Feliksa", "Hilarego", "Martyny" ),
			"15" => array( "Arnolda", "Dory", "Paw³a" ),
			"16" => array( "Mascelego", "Walerii", "W³odzimierza" ),
			"17" => array( "Antoniego", "Henryki", "Mariana" ),
			"18" => array( "Beatrycze", "Ma³gorzaty", "Piotra" ),
			"19" => array( "Erwiny", "Henryka", "Mariusza" ),
			"20" => array( "Fabioli", "Mi³y", "Sebastiana" ),
			"21" => array( "Agnieszki", "Jaros³awa", "Nory" ),
			"22" => array( "Dominiki", "Mateusza", "Wincentego" ),
			"23" => array( "Fernandy", "Jana", "Rajmundy" ),
			"24" => array( "Felicji", "Roberta", "S³awy" ),
			"25" => array( "Mi³osza", "Paw³a", "Tatiany" ),
			"26" => array( "Lutos³awa", "Normy", "Pauliny" ),
			"27" => array( "Anieli", "Juliana", "Przemys³awa" ),
			"28" => array( "Agnieszki", "Kariny", "Les³awa" ),
			"29" => array( "Franciszka", "Konstancji", "Salomei" ),
			"30" => array( "Martyny", "Macieja", "Teofila" ),
			"31" => array( "Joanny", "Ksawerego", "Luizy" )
		), 
		"2" => array( 
			"1"  => array( "Brygidy", "Dobrogniewa", "Ignacego" ),
			"2"  => array( "Kornela", "Marii", "Miros³awy" ),
			"3"  => array( "B³a¿eja", "Joanny", "Telimeny" ),
			"4"  => array( "Andrzeja", "Mariusza", "Weroniki" ),
			"5"  => array( "Agaty", "Filipa", "Justyniana" ),
			"6"  => array( "Amandy", "Bogdana", "Doroty" ),
			"7"  => array( "Ryszarda", "Teodora", "Wilhelminy" ),
			"8"  => array( "Irminy", "Piotra", "Sylwii" ),
			"9"  => array( "Bernarda", "Eryki", "Rajmunda" ),
			"10" => array( "Elwiry", "Elizy", "Jacka" ),
			"11" => array( "Bernadetty", "Marii", "Olgierda" ),
			"12" => array( "Czas³awa", "Damiana", "Normy" ),
			"13" => array( "Grzegorza", "Les³awa", "Katarzyny" ),
			"14" => array( "Liliany", "Walentyny", "Walentego" ),
			"15" => array( "Arnolda", "Jowity", "Georginy" ),
			"16" => array( "Danuty", "Daniela", "Juliany" ),
			"17" => array( "Donata", "Gizeli", "£ukasza" ),
			"18" => array( "Konstancji", "Krystiana", "Sylwany" ),
			"19" => array( "Bettiny", "Konrada", "Miros³awa" ),
			"20" => array( "Anety", "Lehca", "Leona" ),
			"21" => array( "Eleonory", "Lenki", "Kiejstuta" ),
			"22" => array( "Ma³gorzaty", "Marty", "Nikifora" ),
			"23" => array( "Damiana", "Romana", "Romany" ),
			"24" => array( "Boguty", "Bogusza", "Macieja" ),
			"25" => array( "Almy", "Cezarego", "Jaros³awa" ),
			"26" => array( "Bogumi³a", "Eweliny", "Miros³awa" ),
			"27" => array( "Gagrieli", "Liwii", "Leonarda" ),
			"28" => array( "Ludomira", "Makarego", "Wiliany" ),
			"29" => array( "Lecha", "Lutomira", "Wiktora" )
		), 
		"3" => array( 
			"1"  => array( "Albina", "Antoniny", "Rados³awy" ),
			"2"  => array( "Halszki", "Heleny", "Karola" ),
			"3"  => array( "Kingi", "Maryna", "Tycjana" ),
			"4"  => array( "Adrianny", "Kazimierza", "Wac³awa" ),
			"5"  => array( "Aurory", "Fryderyka", "Oliwii" ),
			"6"  => array( "Jordana", "Marcina", "Ró¿y" ),
			"7"  => array( "Flicyty", "Kajetana", "Pauli" ),
			"8"  => array( "Beaty", "Juliana", "Wincentego" ),
			"9"  => array( "Dominika", "Franciszki", "Katarzyny" ),
			"10" => array( "Bo¿ys³awy", "Cypriana", "Marcelego" ),
			"11" => array( "Konstantego", "Ludos³awa", "Rozyny" ),
			"12" => array( "Grzegorza", "Justyny", "Józefiny" ),
			"13" => array( "Bo¿eny", "Krystyny", "Marka" ),
			"14" => array( "Dalii", "Leona", "Matyldy" ),
			"15" => array( "Delfiny", "Longina", "Ludwiki" ),
			"16" => array( "Izabeli", "Henryka", "Oktawii" ),
			"17" => array( "Reginy", "Patryka", "Zdyszka" ),
			"18" => array( "Edwarda", "Narcyza", "Zbys³awa" ),
			"19" => array( "Aleksandryny", "Józefa", "Nicety" ),
			"20" => array( "Joachima", "Kiry", "Maurycego" ),
			"21" => array( "Benedykta", "Lubomiry", "Lubomira" ),
			"22" => array( "Bogus³awa", "Jagody", "Katarzyny" ),
			"23" => array( "Feliksa", "Konrada", "Zbys³awy" ),
			"24" => array( "Gabrieli", "Marka", "Seweryna" ),
			"25" => array( "Bolka", "Cezaryny", "Marioli" ),
			"26" => array( "Dory", "Olgi", "Teodora" ),
			"27" => array( "Ernesta", "Jana", "Marka" ),
			"28" => array( "Anieli", "Kasrota", "Soni" ),
			"29" => array( "Marka", "Wiktoryny", "Zenona" ),
			"30" => array( "Amelii", "Dobromira", "Leonarda" ),
			"31" => array( "Balbiny", "Kamila", "Kornelii" )
		),  
		"4" => array( 
			"1"  => array( "Chryzamtyny", "Gra¿yny", "Zygmunta" ),
			"2"  => array( "Franciszka", "Malwiny", "W³adys³awa" ),
			"3"  => array( "Pankracego", "Renaty", "Ryszarda" ),
			"4"  => array( "Benedykta", "Izodory", "Wac³awy" ),
			"5"  => array( "Ireny", "Kleofasa", "Wincentego" ),
			"6"  => array( "Ady", "Celestyny", "Ireneusza" ),
			"7"  => array( "Donata", "Herminy", "Rufina" ),
			"8"  => array( "Amadeusza", "Cezaryny", "Juliany" ),
			"9"  => array( "Mai", "Marcelego", "Wadima" ),
			"10" => array( "Borys³awy", "Makarego", "Micha³a" ),
			"11" => array( "Filipa", "Izoldy", "Leona" ),
			"12" => array( "Juliusza", "Lubos³awa", "Wiktoryny" ),
			"13" => array( "Artemona", "Justyny", "Przemys³awy" ),
			"14" => array( "Bernarda", "Martyny", "Waleriana" ),
			"15" => array( "Adolfiny", "Odetty", "Wac³awa" ),
			"16" => array( "Bernarda", "Biruty", "Erwina" ),
			"17" => array( "Anicety", "Klary", "Rudolfina" ),
			"18" => array( "Apoloniusza", "Bogus³awy", "Go¶cis³awy" ),
			"19" => array( "Alfa", "Leonii", "Tytusa" ),
			"20" => array( "Agnieszki", "Amalii", "Czecha" ),
			"21" => array( "Jaros³awa", "Konrada", "Selmy" ),
			"22" => array( "£ukasza", "Kai", "Nastazji" ),
			"23" => array( "Ilony", "Jerzego", "Wojciecha" ),
			"24" => array( "Bony", "Horacji", "Jerzego" ),
			"25" => array( "Jaros³awa", "Marka", "Wiki" ),
			"26" => array( "Marii", "Marzeny", "Ryszarda" ),
			"27" => array( "Sergiusza", "Teofila", "Zyty" ),
			"28" => array( "Bogny", "Walerii", "Witalisa" ),
			"29" => array( "Hugona", "Piotra", "Roberty" ),
			"30" => array( "Balladyny", "Lilli", "Mariana" )
		),  
		"5" => array( 
			"1"  => array( "Józefa", "Lubomira", "Ramony" ),
			"2"  => array( "Longiny", "Toli", "Zygmunta" ),
			"3"  => array( "Jarope³ka", "Marii", "Niny" ),
			"4"  => array( "Floriana", "Micha³a", "Moniki" ),
			"5"  => array( "Irydy", "Tamary", "Waldemara" ),
			"6"  => array( "Beniny", "Filipa", "Judyty" ),
			"7"  => array( "Augusta", "Gizeli", "Ludomiry" ),
			"8"  => array( "Kornela", "Lizy", "Stanis³awa" ),
			"9"  => array( "Grzegorza", "Karoliny", "Karola" ),
			"10" => array( "Antoniny", "Izydory", "Jana" ),
			"11" => array( "Igi", "Mamerta", "Miry" ),
			"12" => array( "Dominika", "Imeldy", "Pankracego" ),
			"13" => array( "Agnieszki", "Magdaleny", "Serwacego" ),
			"14" => array( "Bonifacego", "Julity", "Macieja" ),
			"15" => array( "Dionizego", "Nadziei", "Zofii" ),
			"16" => array( "Andrzeja", "Jêdrzeja", "Ma³gorzaty" ),
			"17" => array( "Brunony", "S³awomira", "Wery" ),
			"18" => array( "Alicji", "Edwina", "Eryka" ),
			"19" => array( "Celestyny", "Iwony", "Piotra" ),
			"20" => array( "Bazylego", "Bernardyna", "Krystyny" ),
			"21" => array( "Jana", "Moniki", "Wiktora" ),
			"22" => array( "Emila", "Neleny", "Romy" ),
			"23" => array( "Leoncjusza", "Micha³a", "Renaty" ),
			"24" => array( "Joanny", "Zdenka", "Zuzanny" ),
			"25" => array( "Borysa", "Magdy", "Marii-Magdaleny" ),
			"26" => array( "Eweliny", "Jana", "Paw³a" ),
			"27" => array( "Amandy", "Jana", "Juliana" ),
			"28" => array( "Augustyna", "Ingi", "Jaromira" ),
			"29" => array( "Benity", "Maksymiliana", "Teodozji" ),
			"30" => array( "Ferdynanda", "Gryzeldy", "Zyndrama" ),
			"31" => array( "Anieli", "Feliksa", "Kamili" )
		),  
		"6" => array( 
			"1"  => array( "Gracji", "Jakuba", "Konrada" ),
			"2"  => array( "Erazma", "Marianny", "Marzeny" ),
			"3"  => array( "Anatola", "Leszka", "Tamary" ),
			"4"  => array( "Christy", "Helgi", "Karola" ),
			"5"  => array( "Bonifacego", "Kiry", "Waltera" ),
			"6"  => array( "Laury", "Laurentego", "Nory" ),
			"7"  => array( "Ariadny", "Jaros³awa", "Roberta" ),
			"8"  => array( "Ady", "Celii", "Medarda" ),
			"9"  => array( "Anny-Marii", "Felicjana", "S³awoja" ),
			"10" => array( "Bogumi³a", "Diany", "Ma³gorzaty" ),
			"11" => array( "Barnaby", "Benedykta", "Flory" ),
			"12" => array( "Gwidona", "Leonii", "Niny" ),
			"13" => array( "Antoniego", "Gracji", "Lucjana" ),
			"14" => array( "Bazylego", "Elizy", "Justyny" ),
			"15" => array( "Jolanty", "Lotara", "Wita" ),
			"16" => array( "Aliny", "Anety", "Benona" ),
			"17" => array( "Laury", "Leszka", "Marcjana" ),
			"18" => array( "El¿biety", "Marka", "Pauli" ),
			"19" => array( "Gerwazego", "Protazego", "Sylwii" ),
			"20" => array( "Bogny", "Rafaeli", "Rafa³a" ),
			"21" => array( "Alicji", "Alojzego", "Rudolfa" ),
			"22" => array( "Pauliny", "Sabiny", "Tomasza" ),
			"23" => array( "Albina", "Wandy", "Zenona" ),
			"24" => array( "Danuty", "Jana", "Janiny" ),
			"25" => array( "£ucji", "Witolda", "Wilhelma" ),
			"26" => array( "Jana", "Pauliny", "Rudolfiny" ),
			"27" => array( "Cypriana", "Emanueli", "W³adys³awa" ),
			"28" => array( "Florentyny", "Ligii", "Leona" ),
			"29" => array( "Paw³a", "Piotra", "Salomei" ),
			"30" => array( "Arnolda", "Emiliany", "Lucyny" )
		), 
		"7" => array( 
			"1"  => array( "Bogusza", "Haliny", "Mariana" ),
			"2"  => array( "Kariny", "Serafiny", "Urbana" ),
			"3"  => array( "Anatola", "Jacka", "Miros³awy" ),
			"4"  => array( "Aureli", "Malwiny", "Zygfryda" ),
			"5"  => array( "Antoniego", "Bart³omieja", "Karoliny" ),
			"6"  => array( "Dominiki", "Jarope³ka", "£ucji" ),
			"7"  => array( "Estery", "Kiry", "Rudolfa" ),
			"8"  => array( "Arnolda", "Edgara", "El¿biety" ),
			"9"  => array( "Hieronima", "Palomy", "Weroniki" ),
			"10" => array( "Filipa", "Sylwany", "Witalisa" ),
			"11" => array( "Benedykta", "Kariny", "Olgi" ),
			"12" => array( "Brunona", "Jana", "Wery" ),
			"13" => array( "Danieli", "Irwina", "Ma³gorzaty" ),
			"14" => array( "Kamili", "Kamila", "Marcelego" ),
			"15" => array( "Henryka", "Igi", "W³odzimierza" ),
			"16" => array( "Eustachego", "Mariki", "Mirelli" ),
			"17" => array( "Aleksego", "Bogdana", "Martyny" ),
			"18" => array( "Kamila", "Karoliny", "Roberta" ),
			"19" => array( "Alfreny", "Rufina", "Wincentego" ),
			"20" => array( "Fryderyka", "Ma³gorzaty", "Seweryny" ),
			"21" => array( "Danieli", "Wawrzyñca", "Wiktora" ),
			"22" => array( "Magdaleny", "Mileny", "Wawrzyñca" ),
			"23" => array( "S³awy", "S³awosza", "¯elis³awy" ),
			"24" => array( "Kingi", "Krystyna", "Michaliny" ),
			"25" => array( "Jakuba", "Krzysztofa", "Walentyny" ),
			"26" => array( "Anny", "Miros³awy", "Joachima" ),
			"27" => array( "Aureliusza", "Natalii", "Rudolfa" ),
			"28" => array( "Ady", "Wiwiany", "Sylwiusza" ),
			"29" => array( "Marty", "Konstantego", "Olafa" ),
			"30" => array( "Julity", "Ludmi³y", "Zdobys³awa" ),
			"31" => array( "Ignacego", "Lodomiry", "Romana" )
		),  
		"8" => array( 
			"1"  => array( "Jaros³awa", "Justyny", "Nadziei" ),
			"2"  => array( "Gustawa", "Kariny", "Stefana" ),
			"3"  => array( "Augustyna", "Kamelii", "Lidii" ),
			"4"  => array( "Dominiki", "Dominika", "Protazego" ),
			"5"  => array( "Emila", "Karoliny", "Kary" ),
			"6"  => array( "Jakuba", "S³awy", "Wincentego" ),
			"7"  => array( "Donaty", "Olechny", "Kajetana" ),
			"8"  => array( "Izy", "Rajmunda", "Seweryna" ),
			"9"  => array( "Klary", "Romana", "Rozyny" ),
			"10" => array( "Bianki", "Borysa", "Wawrzyñca" ),
			"11" => array( "Luizy", "W³odzmierza", "Zuzanny" ),
			"12" => array( "Hilarii", "Juliana", "Lecha" ),
			"13" => array( "Elwiry", "Hipolita", "Rados³awy" ),
			"14" => array( "Alfreda", "Maksymiliana", "Selmy" ),
			"15" => array( "Marii", "Napoleona", "Stelli" ),
			"16" => array( "Joachima", "Nory", "Stefana" ),
			"17" => array( "Anity", "Elizy", "Mirona" ),
			"18" => array( "Bogus³awa", "Bronis³awa", "Ilony" ),
			"19" => array( "Emilii", "Julinana", "Konstancji" ),
			"20" => array( "Bernarda", "Sabiny", "Samuela" ),
			"21" => array( "Franciszka", "Kazimiery", "Ruty" ),
			"22" => array( "Cezarego", "Marii", "Zygfryda" ),
			"23" => array( "Apolinarego", "Mi³y", "Ró¿y" ),
			"24" => array( "Bartosza", "Jerzego", "Maliny" ),
			"25" => array( "Belii", "Ludwika", "Luizy" ),
			"26" => array( "Ireneusza", "Konstantego", "Marii" ),
			"27" => array( "Cezarego", "Ma³gorzaty", "Moniki" ),
			"28" => array( "Adeliny", "Erazma", "Sobies³awa" ),
			"29" => array( "Beaty", "Racibora", "Sabiny" ),
			"30" => array( "Benona", "Jowity", "Szczêsnego" ),
			"31" => array( "Ckubyrusa", "Izabeli", "Rajmundy" )
		),  
		"9" => array( 
			"1"  => array( "Belindy", "Bronisza", "Idziego" ),
			"2"  => array( "Dionizy", "Izy", "Juliana" ),
			"3"  => array( "Joachima", "Liliany", "Szymona" ),
			"4"  => array( "Dalii", "Idy", "Rocha" ),
			"5"  => array( "Doroty", "Justyna", "Wawrzyñca" ),
			"6"  => array( "Beaty", "Eugeniusza", "Lidy" ),
			"7"  => array( "Reginy", "Marka", "Melchiora" ),
			"8"  => array( "Czcibora", "Marii", "Rados³awa" ),
			"9"  => array( "Aldony", "Jakuba", "Sergiusza" ),
			"10" => array( "Eligii", "Irmy", "£ukasza" ),
			"11" => array( "Dagny", "Jacka", "Prota" ),
			"12" => array( "Amadeusza", "Gwidy", "Sylwiny" ),
			"13" => array( "Apolinarego", "Eugenii", "Lubomira" ),
			"14" => array( "Bernarda", "Mony", "Roksany" ),
			"15" => array( "Albina", "Lolity", "Ronalda" ),
			"16" => array( "Jagienki", "Kamili", "Korneliusza" ),
			"17" => array( "Franciszka", "Lamberty", "Narcyza" ),
			"18" => array( "Ireny", "Irminy", "Stanis³awa" ),
			"19" => array( "Januarego", "Konstancji", "Leopolda" ),
			"20" => array( "Eustachego", "Faustyny", "Renaty" ),
			"21" => array( "Darii", "Mateusza", "Wawrzyñca" ),
			"22" => array( "Maury", "Milany", "Tomasza" ),
			"23" => array( "Bogus³awa", "Liwiusza", "Tekli" ),
			"24" => array( "Dory", "Gerarda", "Maryny" ),
			"25" => array( "Aureli", "Kamila", "Kleofasa" ),
			"26" => array( "Cypriana", "Justyny", "£ucji" ),
			"27" => array( "Damiana", "Mirabeli", "Wincentego" ),
			"28" => array( "Libuszy", "Wac³awy", "Wac³awa" ),
			"29" => array( "Michaliny", "Micha³a", "Rafa³a" ),
			"30" => array( "Geraldy", "Honoriusza", "Wery" )
		),  
		"10" => array( 
			"1"  => array( "Heloizy", "Igora", "Remigiusza" ),
			"2"  => array( "Racheli", "S³awy", "Teofila" ),
			"3"  => array( "Bogumi³a", "Gerarda", "Józefy" ),
			"4"  => array( "Edwina", "Ros³awy", "Rozalii" ),
			"5"  => array( "Flawii", "Justyna", "Rajmunda" ),
			"6"  => array( "Artura", "Fryderyki", "Petry" ),
			"7"  => array( "Krystyna", "Marii", "Marka" ),
			"8"  => array( "Brygidy", "Loreny", "Marcina" ),
			"9"  => array( "Arnolda", "Ludwika", "Sybili" ),
			"10" => array( "Franciszka", "Loretty", "Poli" ),
			"11" => array( "Aldony", "Brunona", "Emila" ),
			"12" => array( "Krystyny", "Maksa", "Serafiny" ),
			"13" => array( "Edwarda", "Geraldyny", "Teofila" ),
			"14" => array( "Alany", "Damiana", "Liwii" ),
			"15" => array( "Jadwigi", "Leonarda", "Teresy" ),
			"16" => array( "Ambro¿ego", "Florentyny", "Gaw³a" ),
			"17" => array( "Antonii", "Ignacego", "Wiktora" ),
			"18" => array( "Hanny", "Klementyny", "£ukasza" ),
			"19" => array( "Michaliny", "Micha³a", "Piotra" ),
			"20" => array( "Ireny", "Kleopatry", "Witalisa" ),
			"21" => array( "Celiny", "Hilarego", "Janusza" ),
			"22" => array( "Haliszki", "Lody", "Przybys³awa" ),
			"23" => array( "Edwarda", "Marleny", "Seweryna" ),
			"24" => array( "Arety", "Marty", "Marcina" ),
			"25" => array( "Ingi", "Maurycego", "Sambora" ),
			"26" => array( "Ewarysta", "Lucyny", "Lutos³awy" ),
			"27" => array( "Iwony", "Noemi", "Szymona" ),
			"28" => array( "Narcyza", "Serafina", "Wioletty" ),
			"29" => array( "Angeli", "Przemys³awa", "Zenobii" ),
			"30" => array( "Augustyny", "£ukasza", "Urbana" ),
			"31" => array( "Krzysztofa", "Augusta", "Saturnina" )
		),  
		"11" => array( 
			"1"  => array( "Konrada", "Seweryny", "Wiktoryny" ),
			"2"  => array( "Bohdany", "Henryka", "Tobiasza" ),
			"3"  => array( "Huberta", "Mi³y", "Sylwii" ),
			"4"  => array( "Albertyny", "Karola", "Olgierda" ),
			"5"  => array( "Balladyny", "El¿biety", "S³awomira" ),
			"6"  => array( "Arletty", "Feliksa", "Leonarda" ),
			"7"  => array( "Antoniego", "Kaliny", "Przemi³y" ),
			"8"  => array( "Klaudii", "Seweryna", "Wiktoriusza" ),
			"9"  => array( "Anatolii", "Gracji", "Teodora" ),
			"10" => array( "Leny", "Lubomira", "Natalii" ),
			"11" => array( "Bart³omieja", "Gertrudy", "Marcina" ),
			"12" => array( "Konrada", "Renaty", "Witolda" ),
			"13" => array( "Arkadii", "Krystyna", "Stanis³awy" ),
			"14" => array( "Emila", "Laury", "Rogera" ),
			"15" => array( "Amielii", "Idalii", "Leopolda" ),
			"16" => array( "Edmunda", "Marii", "Marka" ),
			"17" => array( "Grzegorza", "Salomei", "Walerii" ),
			"18" => array( "Klaudyny", "Romana", "Tomasza" ),
			"19" => array( "El¿biety", "Faustyny", "Paw³a" ),
			"20" => array( "Anatola", "Edyty", "Rafa³a" ),
			"21" => array( "Janusza", "Marii", "Reginy" ),
			"22" => array( "Cecylii", "Jonatana", "Marka" ),
			"23" => array( "Adeli", "Felicyty", "Klemensa" ),
			"24" => array( "Emmy", "Flory", "Romana" ),
			"25" => array( "El¿biety", "Katarzyny", "Klemensa" ),
			"26" => array( "Leona", "Leonarda", "Les³awy" ),
			"27" => array( "Franciszka", "Kseni", "Maksymiliana" ),
			"28" => array( "Jakuba", "Stefana", "Romy" ),
			"29" => array( "B³a¿eja", "Margerity", "Saturnina" ),
			"30" => array( "Andrzeja", "Maury", "Ondraszka" )
		),  
		"12" => array( 
			"1"  => array( "Blanki", "Edmunda", "Eligiusza" ),
			"2"  => array( "Balbiny", "Ksawerego", "Pauliny" ),
			"3"  => array( "Hilarego", "Franciszki", "Ksawery" ),
			"4"  => array( "Barbary", "Hieronima", "Krystiana" ),
			"5"  => array( "Kryspiny", "Norberta", "Sabiny" ),
			"6"  => array( "Dionizji", "Leontyny", "Miko³aja" ),
			"7"  => array( "Agaty", "Dalii", "Sobies³awa" ),
			"8"  => array( "Delfiny", "Marii", "Wirginiusza" ),
			"9"  => array( "Anety", "Leokadii", "Wies³awa" ),
			"10" => array( "Danieli", "Bohdana", "Julii" ),
			"11" => array( "Biny", "Damazego", "Waldemara" ),
			"12" => array( "Ady", "Aleksandra", "Dagmary" ),
			"13" => array( "Dalidy", "Juliusza", "£ucji" ),
			"14" => array( "Alfreda", "Izydora", "Zoriny" ),
			"15" => array( "Celiny", "Ireneusza", "Niny" ),
			"16" => array( "Albiny", "Sebastiana", "Zdzis³awy" ),
			"17" => array( "Jolanty", "£ukasza", "Olimpii" ),
			"18" => array( "Bogus³awa", "Gracjana", "Laury" ),
			"19" => array( "Beniaminy", "Dariusza", "Gabrieli" ),
			"20" => array( "Bogumi³y", "Dominika", "Zefiryna" ),
			"21" => array( "Honoraty", "Seweryny", "Tomasza" ),
			"22" => array( "Bo¿eny", "Drogomira", "Zenona" ),
			"23" => array( "Dagny", "S³awomiry", "Wiktora" ),
			"24" => array( "Adama", "Ewy", "Irminy" ),
			"25" => array( "Anety", "Glorii", "Piotra" ),
			"26" => array( "Dionizego", "Kaliksta", "Szczepana" ),
			"27" => array( "Fabioli", "Jana", "¯anety" ),
			"28" => array( "Antoniusza", "Cezarego", "Teofilii" ),
			"29" => array( "Dawida", "Dionizy", "Tomasza" ),
			"30" => array( "Eugeniusza", "Katarzyny", "Sabiny" ),
			"31" => array( "Mariusza", "Melanii", "Sylwestra" )
		)
	); 
	
	 
	/**
	 * Constructor
	 *
	 * @access public
	 */
	function Date_Namedays_pl( $params = array() )
	{
		$this->Date_Namedays( $params );
	}
} // END OF Date_Namedays_pl

?>
