<?php

/*
+----------------------------------------------------------------------+
|This program is free software; you can redistribute it and/or modify  |
|it under the terms of the GNU General Public License as published by  |
|the Free Software Foundation; either version 2 of the License, or     |
|(at your option) any later version.                                   |
|                                                                      |
|This program is distributed in the hope that it will be useful,       |
|but WITHOUT ANY WARRANTY; without even the implied warranty of        |
|MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the          |
|GNU General Public License for more details.                          |
|                                                                      |
|You should have received a copy of the GNU General Public License     |
|along with this program; if not, write to the Free Software           |
|Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.             |
+----------------------------------------------------------------------+
|Authors: Markus Nix <mnix@docuverse.de>                               |
|         Ferenc Raffael <raffaelf@interware.hu>                       |
+----------------------------------------------------------------------+
*/


using( 'util.datetime.namedays.lib.Date_Namedays' );


/**
 * @package util_datetime_namedays_lib
 */
 
class Date_Namedays_hu extends Date_Namedays
{
	/**
	 * Array of Namedays
	 *
	 * @var    array
	 * @access private
	 */
	var $_namedays = array(
		"1" => array(
			"1"  => array( "Újév", "Fruzsina" ), 
			"2"  => "Ábel", 
			"3"  => array( "Genovéva", "Benjámin" ), 
			"4"  => array( "Titusz", "Leona" ), 
			"5"  => "Simon", 
			"6"  => "Boldizsár", 
			"7"  => array( "Attila", "Ramóna" ), 
			"8"  => "Gyöngyvér", 
			"9"  => "Marcell", 
			"10" => "Melánia", 
			"11" => "Ágota", 
			"12" => "Ernõ", 
			"13" => "Veronika", 
			"14" => "Bódog", 
			"15" => array( "Lóránt", "Lóránd" ), 
			"16" => "Gusztáv", 
			"17" => array( "Antal", "Antónia" ), 
			"18" => "Piroska", 
			"19" => array( "Sára", "Márió" ), 
			"20" => array( "Fábián", "Sebestyén" ), 
			"21" => "Ágnes", 
			"22" => array( "Vince", "Artúr" ), 
			"23" => array( "Zelma", "Rajmund" ), 
			"24" => "Timót", 
			"25" => "Pál", 
			"26" => array( "Vanda", "Paula" ), 
			"27" => "Angelika", 
			"28" => array( "Károly", "Karola" ), 
			"29" => "Adél",
			"30" => array( "Martina", "Gerda" ), 
			"31" => "Marcella"
		),
		"2" => array(
			"1"  => "Ignác", 
			"2"  => array( "Karolina", "Aida" ), 
			"3"  => "Balázs", 
			"4"  => array( "Ráhel", "Csenge" ), 
			"5"  => array( "Ágota", "Ingrid" ), 
			"6"  => array( "Dorottya", "Dóra" ), 
			"7"  => array( "Tódor", "Rómeó" ), 
			"8"  => "Aranka", 
			"9"  => array( "Abigél", "Alex" ), 
			"10" => "Elvira", 
			"11" => array( "Bertold", "Marietta" ), 
			"12" => array( "Lídia", "Lívia" ), 
			"13" => array( "Ella", "Linda" ), 
			"14" => array( "Valentin nap", "Bálint" ), 
			"15" => array( "Kolos", "Georgina" ), 
			"16" => array( "Julianna", "Lilla" ), 
			"17" => "Donát", 
			"18" => "Bernadett", 
			"19" => "Zsuzsanna", 
			"20" => array( "Aladár", "Álmos" ), 
			"21" => "Eleonóra", 
			"22" => "Gerzson", 
			"23" => "Alfréd", 
			"24" => "Szökõnap", 
			"25" => "Mátyás", 
			"26" => "Géza", 
			"27" => "Edina", 
			"28" => array( "Ákos", "Bátor" ), 
			"29" => "Elemér"
		), 
		"3" => array(
			"1"  => "Albin", 
			"2"  => "Lujza", 
			"3"  => "Kornélia", 
			"4"  => "Kázmér", 
			"5"  => array( "Adorján", "Adrián" ), 
			"6"  => array( "Leonóra", "Inez" ), 
			"7"  => "Tamás", 
			"8"  => array( "Nõnap", "Zoltán" ), 
			"9"  => array( "Franciska", "Fanni" ), 
			"10" => "Ildikó", 
			"11" => "Szilárd", 
			"12" => "Gergely", 
			"13" => array( "Krisztián", "Ajtóny" ), 
			"14" => "Matild", 
			"15" => array( "Nemzeti ünnep", "Kristóf" ), 
			"16" => "Henrietta", 
			"17" => array( "Gertrúd", "Patrik" ), 
			"18" => array( "Sándor", "Ede" ), 
			"19" => array( "József", "Bánk" ), 
			"20" => "Klaudia", 
			"21" => "Benedek", 
			"22" => array( "Beáta", "Izolda" ), 
			"23" => "Emõke", 
			"24" => array( "Gábor", "Karina" ), 
			"25" => array( "Irén", "Írisz" ), 
			"26" => "Emánuel", 
			"27" => "Hajnalka", 
			"28" => array( "Gedeon", "Johanna" ), 
			"29" => "Auguszta", 
			"30" => "Zalán", 
			"31" => "Árpád"
		), 
		"4" => array(
			"1"  => "Hugó", 
			"2"  => "Áron", 
			"3"  => array( "Buda", "Richárd" ), 
			"4"  => "Izidor", 
			"5"  => "Vince", 
			"6"  => array( "Vilmos", "Bíborka" ), 
			"7"  => "Herman", 
			"8"  => "Dénes", 
			"9"  => "Erhard", 
			"10" => "Zsolt", 
			"11" => array( "Leó", "Szaniszló" ), 
			"12" => "Gyula", 
			"13" => "Ida", 
			"14" => "Tibor", 
			"15" => array( "Anasztázia", "Tas" ), 
			"16" => "Csongor", 
			"17" => "Rudolf", 
			"18" => array( "Andrea", "Ilma" ), 
			"19" => "Emma", 
			"20" => "Tivadar", 
			"21" => "Konrád", 
			"22" => array( "Csilla", "Noémi" ), 
			"23" => "Béla", 
			"24" => "György", 
			"25" => "Márk", 
			"26" => "Ervin", 
			"27" => array( "Zita", "Mariann" ), 
			"28" => "Valéria", 
			"29" => "Péter", 
			"30" => array( "Katalin", "Kitti" )
		), 
		"5" => array(
			"1"  => array( "Munka ünnepe", "Fülöp", "Jakab" ), 
			"2"  => "Zsigmond", 
			"3"  => array( "Tímea", "Irma" ), 
			"4"  => array( "Mónika", "Flórián" ), 
			"5"  => "Györgyi", 
			"6"  => array( "Ivett", "Frida" ), 
			"7"  => "Gizella", 
			"8"  => "Mihély", 
			"9"  => "Gergely",
			"10" => array( "Ármin", "Palma" ), 
			"11" => "Ferenc", 
			"12" => "Pongrác", 
			"13" => array( "Szervác", "Imola" ), 
			"14" => "Bonifác", 
			"15" => array( "Zsófia", "Szonja" ), 
			"16" => array( "Mózes", "Botond" ), 
			"17" => "Paszkál", 
			"18" => array( "Erik", "Alexandra" ), 
			"19" => array( "Ivó", "Milán" ), 
			"20" => array( "Bernát", "Felícia" ), 
			"21" => "Konstantin", 
			"22" => array( "Júlia", "Rita" ), 
			"23" => "Dezsõ", 
			"24" => array( "Eszter", "Eliza" ), 
			"25" => "Orbán", 
			"26" => array( "Fülöp", "Evelin" ), 
			"27" => "Hella", 
			"28" => array( "Emil", "Csanád" ), 
			"29" => "Magdolna", 
			"30" => array( "Janka", "Zsanett" ), 
			"31" => array( "Angéla", "Petronella" )
		), 
		"6" => array(
			"1"  => "Tünde", 
			"2"  => array( "Kármen", "Anita" ), 
			"3"  => "Klotild", 
			"4"  => "Bulcsú", 
			"5"  => "Fatime", 
			"6"  => array( "Norbert", "Cintia" ), 
			"7"  => "Róbert", 
			"8"  => "Medárd", 
			"9"  => "Félix", 
			"10" => array( "Margit", "Gréta" ), 
			"11" => "Barnabás", 
			"12" => "Villõ", 
			"13" => array( "Antal", "Anett" ), 
			"14" => "Vazul", 
			"15" => array( "Jolán", "Vid" ), 
			"16" => "Jusztin", 
			"17" => array( "Laura", "Alida" ), 
			"18" => array( "Arnold", "Levente" ), 
			"19" => "Gyárfás", 
			"20" => "Rafael", 
			"21" => array( "Alajos", "Leila" ), 
			"22" => "Paulina", 
			"23" => "Zoltán", 
			"24" => "Iván", 
			"25" => "Vilmos", 
			"26" => array( "János", "Pál" ), 
			"27" => "László", 
			"28" => array( "Levente", "Irén" ), 
			"29" => array( "Péter", "Pál" ), // ? 
			"30" => "Pál"
		), 
		"7" => array(
			"1"  => array( "Tihamér", "Annamária" ), 
			"2"  => "Ottó", 
			"3"  => array( "Kornél", "Soma" ), 
			"4"  => "Ulrik", 
			"5"  => array( "Emese", "Sarolta" ), 
			"6"  => "Csaba", 
			"7"  => "Apollónia", 
			"8"  => "Ellák", 
			"9"  => "Lukrécia", 
			"10" => "Amália", 
			"11" => array( "Mára", "Lili" ), 
			"12" => array( "Izabella", "Dalma" ), 
			"13" => "Jenõ", 
			"14" => array( "Örs", "Stella" ), 
			"15" => array( "Henrik", "Roland" ), 
			"16" => "Valter", 
			"17" => array( "Endre", "Elek" ), 
			"18" => "Frigyes", 
			"19" => "Emília", 
			"20" => "Illés", 
			"21" => array( "Dániel", "Daniella" ), 
			"22" => "Magdolna", 
			"23" => "Lenke", 
			"24" => array( "Kinga", "Kicsõ" ), 
			"25" => array( "Kristóf", "Jakab" ), 
			"26" => array( "Anna", "Anikó" ), 
			"27" => array( "Olga", "Liliána" ), 
			"28" => "Szabolcs", 
			"29" => array( "Márta", "Flóra" ), 
			"30" => array( "Judit", "Xénia" ), 
			"31" => "Oszkár"
		), 
		"8" => array(
			"1"  => "Boglárka", 
			"2"  => "Lehel", 
			"3"  => "Hermina", 
			"4"  => array( "Domonkos", "Dominika" ), 
			"5"  => "Krisztina", 
			"6"  => array( "Berta", "Bettina" ), 
			"7"  => "Ibolya", 
			"8"  => "László", 
			"9"  => "Emõd", 
			"10" => "Lõrinc", 
			"11" => array( "Zsuzsanna", "Tiborc" ), 
			"12" => "Klára", 
			"13" => "Ipoly", 
			"14" => "Marcell", 
			"15" => "Mária", 
			"16" => "Ábrahám", 
			"17" => "Jácint", 
			"18" => "Ilona", 
			"19" => "Huba", 
			"20" => array( "Szt István és az államalapítás ünnepe", "Vajk" ), 
			"21" => array( "Samuel", "Hajna" ), 
			"22" => array( "Menyhért", "Mirjam" ), 
			"23" => "Bence", 
			"24" => "Bertalan", 
			"25" => array( "Lajos", "Patrícia" ), 
			"26" => "Izsó", 
			"27" => "Gáspár", 
			"28" => "Ágoston", 
			"29" => array( "Beatrix", "Erna" ), 
			"30" => "Rózsa", 
			"31" => array( "Erika", "Bella" )
		), 
		"9" => array(
			"1"  => array( "Egyed", "Egon" ), 
			"2"  => array( "Rebeka", "Dorina" ), 
			"3"  => "Hilda", 
			"4"  => "Rozália", 
			"5"  => array( "Viktor", "Lõrinc" ), 
			"6"  => "Zakariás", 
			"7"  => "Regina", 
			"8"  => array( "Mária", "Adrienn" ), 
			"9"  => "Ádám", 
			"10" => array( "Nikolett", "Hunor" ), 
			"11" => "Teodóra", 
			"12" => "Mária", 
			"13" => "Kornél", 
			"14" => array( "Szeréna", "Roxána" ), 
			"15" => array( "Enikõ", "Melitta" ), 
			"16" => "Edit", 
			"17" => "Zsófia", 
			"18" => "Diána", 
			"19" => "Vilhelmina", 
			"20" => "Friderika", 
			"21" => array( "Máté", "Mirella" ), 
			"22" => "Móric", 
			"23" => "Tekla", 
			"24" => array( "Gellért", "Mercédesz" ), 
			"25" => array( "Eufrozina", "Kende" ), 
			"26" => "Jusztina", 
			"27" => "Adalbert", 
			"28" => "Vencel", 
			"29" => "Mihály", 
			"30" => "Jeromos"
		), 
		"10" => array(
			"1"  => "Malvin", 
			"2"  => "Petra", 
			"3"  => "Helga", 
			"4"  => "Ferenc", 
			"5"  => "Aurél", 
			"6"  => array( "Brúnó", "Renáta" ), 
			"7"  => "Amália", 
			"8"  => "Koppány", 
			"9"  => "Dénes", 
			"10" => "Gedeon", 
			"11" => array( "Brigitta", "Gitta" ), 
			"12" => "Miksa", 
			"13" => array( "Kálmán", "Ede" ), 
			"14" => "Helén", 
			"15" => "Teréz", 
			"16" => "Gál", 
			"17" => "Hedvig", 
			"18" => "Lukács", 
			"19" => "Nándor", 
			"20" => "Vendel", 
			"21" => "Orsolya", 
			"22" => "Elõd", 
			"23" => array( "Nemzeti ünnep", "Gyöngyi" ), 
			"24" => "Salamon", 
			"25" => array( "Blanka", "Bianka" ), 
			"26" => "Dömötör", 
			"27" => "Szabina", 
			"28" => array( "Simon", "Szimonetta" ), 
			"29" => "Nárcisz", 
			"30" => "Alfonz", 
			"31" => "Farkas"
		), 
		"11" => array(
			"1"  => "Marianna", 
			"2"  => "Achilles", 
			"3"  => "Gyõzõ", 
			"4"  => "Károly", 
			"5"  => "Imre", 
			"6"  => "Lénárd", 
			"7"  => "Rezsõ", 
			"8"  => "Zsombor", 
			"9"  => "Tivadar", 
			"10" => "Réka", 
			"11" => "Márton", 
			"12" => array( "Jónás", "Renátó" ), 
			"13" => "Szilvia", 
			"14" => "Aliz", 
			"15" => array( "Albert", "Lipót" ), 
			"16" => "Ödön", 
			"17" => array( "Hortenzia", "Gergõ" ), 
			"18" => "Jenõ", 
			"19" => array( "Erzsébet", "Zsóka" ), 
			"20" => "Jolán", 
			"21" => "Olivér", 
			"22" => "Cecília", 
			"23" => array( "Kelemen", "Klementina" ), 
			"24" => "Emma",
			"25" => "Katalin", 
			"26" => "Virág", 
			"27" => "Virgil", 
			"28" => "Stefánia", 
			"29" => "Taksony", 
			"30" => array( "András", "Andor" )
		), 
		"12" => array(
			"1"  => "Elza", 
			"2"  => array( "Malinda", "Vivien" ), 
			"3"  => array( "Ferenc", "Olívia" ), 
			"4"  => array( "Borbála", "Barbara" ), 
			"5"  => "Vilma", 
			"6"  => "Miklós", 
			"7"  => "Ambrus", 
			"8"  => "Mária", 
			"9"  => "Natália", 
			"10" => "Judit", 
			"11" => "Árpád", 
			"12" => "Gabriella", 
			"13" => array( "Luca", "Ottília" ), 
			"14" => "Szilárda", 
			"15" => "Valér", 
			"16" => array( "Etelka", "Aletta" ), 
			"17" => array( "Lázár", "Olimpia" ), 
			"18" => "Auguszta", 
			"19" => "Viola", 
			"20" => "Teofil", 
			"21" => "Tamás", 
			"22" => "Zénó", 
			"23" => "Viktória", 
			"24" => array( "Szenteste", "Ádám", "Éva" ), 
			"25" => array( "Karácsony", "Eugénia" ), 
			"26" => array( "Karácsony", "István" ), 
			"27" => "János", 
			"28" => "Kamilla", 
			"29" => array( "Tamás", "Tamara" ), 
			"30" => "Dávid", 
			"31" => "Szilveszter"
		)
	); 
	
	 
	/**
	 * Constructor
	 *
	 * @access public
	 */
	function Date_Namedays_hu( $params = array() )
	{
		$this->Date_Namedays( $params );
	}
} // END OF Date_Namedays_hu

?>
