<?php

/*
+----------------------------------------------------------------------+
|This program is free software; you can redistribute it and/or modify  |
|it under the terms of the GNU General Public License as published by  |
|the Free Software Foundation; either version 2 of the License, or     |
|(at your option) any later version.                                   |
|                                                                      |
|This program is distributed in the hope that it will be useful,       |
|but WITHOUT ANY WARRANTY; without even the implied warranty of        |
|MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the          |
|GNU General Public License for more details.                          |
|                                                                      |
|You should have received a copy of the GNU General Public License     |
|along with this program; if not, write to the Free Software           |
|Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.             |
+----------------------------------------------------------------------+
|Authors: Markus Nix <mnix@docuverse.de>                               |
+----------------------------------------------------------------------+
*/


using( 'commerce.stocks.lib.StockSymbols' );


/**
 * @package commerce_stocks_lib
 */
 
class StockSymbols_MLSE extends StockSymbols
{
	/**
	 * Constructor
	 *
	 * @access public
	 */
	function StockSymbols_MLSE( $options = array() )
	{
		$this->StockSymbols( $options );
		
		$this->_populate();
	}
	
	
	// private methods
	
	/**
	 * @access private
	 */
	function _populate()
	{
		$this->_stock_ex = "Milan Stock Exchange";
		
		$this->_symbols = array(
			"ACE"	=> "Acea Spa",
			"ACO"	=> "Acotel Group",
			"ACP"	=> "Acque Potabili",
			"ACSM"	=> "Acsm Spa",
			"ACT"	=> "Actelios",
			"ADFI"	=> "Acquedot Ferrari",
			"ADMI"	=> "Milano",
			"AEDI"	=> "Aedes",
			"AEG"	=> "Acegas",
			"AEMI"	=> "Aem Spa",
			"AET"	=> "Aem Torino",
			"AFI"	=> "Aeroport Firenze",
			"AIMI"	=> "Attivita",
			"AISW"	=> "Aisoftw@re",
			"ALGL"	=> "Algol",
			"ALZI"	=> "Alleanza",
			"AMBR"	=> "Asm Brescia",
			"AMG"	=> "Amga Spa",
			"AMP"	=> "Amplifon Spa",
			"ANSI"	=> "Ansaldo Trasport",
			"APMI"	=> "Antica Marcia",
			"AQNI"	=> "Acq Nicolay",
			"ARQ"	=> "Arquati",
			"ART"	=> "Art'e'",
			"ASR"	=> "A.s. Roma",
			"AST"	=> "Astaldi Spa",
			"AZPIa"	=> "Alitalia Stk A",
			"BANI"	=> "Bnl",
			"BCNT"	=> "Basicnet",
			"BCPI"	=> "Banca Siracusa",
			"BCRI"	=> "Popolare Di Crem",
			"BDCI"	=> "Bk Chiavari",
			"BDLI"	=> "Banca Di Legnano",
			"BE"	=> "Beghelli Spa",
			"BFFI"	=> "Ferraresi",
			"BIN"	=> "Banca Intesa",
			"BIO"	=> "Biosearch Italia",
			"BISC"	=> "E.biscom",
			"BIZI"	=> "Elios Hldg Milan",
			"BL"	=> "Bca Lombarda",
			"BMAN"	=> "Bk Agr Mantovana",
			"BMPS"	=> "B M Paschi Siena",
			"BNG"	=> "Benetton Group",
			"BNSI"	=> "Beni Stabili",
			"BOEI"	=> "Boero",
			"BPAD"	=> "Bca Pop Adriatic",
			"BPCI"	=> "Bk Pop Comm Ind",
			"BPSI"	=> "Banca Di Sondrio",
			"BPVN"	=> "Bco Pop Vr E No",
			"BRBI"	=> "Brembo",
			"BRGI"	=> "Borgosesia",
			"BRUI"	=> "Brioschi",
			"BSPI"	=> "Spoleto Credito",
			"BSS"	=> "Biesse",
			"BTGI"	=> "Bastogi",
			"BULG"	=> "Bulgari",
			"BVII"	=> "Bayerische Vita",
			"BZU"	=> "Buzzi Unicem Spa",
			"CAD"	=> "Cad It",
			"CAI"	=> "Cairo Comunication",
			"CALI"	=> "Caltagirone",
			"CAMI"	=> "Camfin",
			"CARR"	=> "Carraro",
			"CASS"	=> "Cattolica Ass",
			"CBDI"	=> "Ciriofinanziaria",
			"CBGI"	=> "Cr Bergamasco",
			"CBMI"	=> "Bonaparte Spa",
			"CDC"	=> "Cdc Point Spa",
			"CDN"	=> "Cardnet Group",
			"CED"	=> "Caltagirone Edit",
			"CEMI"	=> "Cementir",
			"CEZI"	=> "Centenar Zinelli",
			"CFI"	=> "Cas Risp Firenze",
			"CHL"	=> "Chl",
			"CIRX"	=> "Cir-comp",
			"CLE"	=> "Class Editori",
			"CLPI"	=> "Calap",
			"CLT"	=> "Cent Latte Torin",
			"CMB"	=> "Cembre",
			"COFI"	=> "Cofide",
			"CPR"	=> "Davide Campari",
			"CPTA"	=> "Capitalia",
			"CRA"	=> "Cr Artigiano",
			"CRDI"	=> "Unicredito Spa",
			"CRE"	=> "Crespi Spa",
			"CRGI"	=> "Banca Carige",
			"CRM"	=> "Cremonini Spa",
			"CSP"	=> "Csp Int Calze",
			"CTO"	=> "Cto",
			"CUCI"	=> "Cucirini",
			"DA"	=> "Dada",
			"DAL"	=> "Datalogic",
			"DALI"	=> "Dalmine",
			"DAM"	=> "Datamat",
			"DANI"	=> "Danieli",
			"DAS"	=> "Data Service",
			"DESI"	=> "Bc Desio Brianza",
			"DIB"	=> "Digital Bros",
			"DLG"	=> "De'longhi",
			"DLM"	=> "Air Dolomiti",
			"DMA"	=> "Dmail",
			"DMH"	=> "Ducati Motor Hld",
			"ED"	=> "Edison",
			"EDII"	=> "Monrif Spa",
			"ELN"	=> "El En",
			"EM"	=> "Emak Spa",
			"EMBI"	=> "Credito Emiliano",
			"EMII"	=> "Banca Emilia",
			"ENEI"	=> "Enel",
			"ENG"	=> "Engineer Inform",
			"ENI"	=> "Eni",
			"ENRT"	=> "Enertad",
			"ERG"	=> "Erg",
			"ESA"	=> "Esaote",
			"ESPI"	=> "L'espresso",
			"EUP"	=> "Euphon",
			"FCAI"	=> "Fincasa",
			"FCDI"	=> "Finarte C Aste",
			"FCO"	=> "Fineco",
			"FDA"	=> "Fidia",
			"FDL"	=> "Freedomland",
			"FDP"	=> "Filatura Pollone",
			"FER"	=> "Ferretti",
			"FIA"	=> "Fiat",
			"FIBK"	=> "Fideuram",
			"FMAT"	=> "Finmatica Aor",
			"FNAI"	=> "Finarte Partecip",
			"FNMI"	=> "Ferr Nord Milano",
			"GABI"	=> "Gabetti",
			"GAIA"	=> "La Gaiana",
			"GAND"	=> "Gandalf",
			"GARI"	=> "Garboli",
			"GASI"	=> "Generali",
			"GC"	=> "Gruppo Coin Spa",
			"GDM"	=> "Gildemeister",
			"GE"	=> "Gefran Spa",
			"GEMI"	=> "Gemina",
			"GEWI"	=> "Gewiss",
			"GIMI"	=> "Gim",
			"GIU"	=> "Itdesgn Giugiaro",
			"GNAV"	=> "Grd. Navi Veloci",
			"GRF"	=> "Granitifiandre",
			"GSG"	=> "Giacomelli Sport",
			"HPI"	=> "Hldg Part Ind",
			"IASI"	=> "La Fondiaria Ass",
			"IF"	=> "Banca Ifis",
			"IFLI"	=> "Ifil",
			"IFPI_p"	=> "Ifi Pr",
			"IG"	=> "Italgas",
			"IGV"	=> "I Grandi Viaggi",
			"IIL"	=> "Inv Imm Lombardi",
			"IMAI"	=> "Ima",
			"IMLO"	=> "Immo. Lombarda",
			"IMMP"	=> "Metanopoli",
			"IMSI"	=> "Immsi",
			"INE"	=> "I.net",
			"INF"	=> "Inferentia Dnm",
			"INT"	=> "Interbanca Spa",
			"IP"	=> "Interpump",
			"IPGI"	=> "Impregilo",
			"IPR"	=> "Idra Presse",
			"IRC"	=> "Irce Spa",
			"IRTI"	=> "Sirti",
			"ISEI"	=> "Locat",
			"ITAI"	=> "Italcementi",
			"ITH"	=> "It Holding",
			"ITMI"	=> "Italmobiliare",
			"ITW"	=> "It Way Spa",
			"JHTI"	=> "Jolly Hotels",
			"JUVE"	=> "Juventus Fc",
			"LAV"	=> "Lavorwash",
			"LDO"	=> "La Doria",
			"LINI"	=> "Linificio",
			"LTM"	=> "Lottomatica Spa",
			"LUX"	=> "Luxottica",
			"MAFI"	=> "Maffei",
			"MARG"	=> "Marangoni",
			"MBFG"	=> "Mariella Burani",
			"MCL"	=> "Marcolin",
			"MDBI"	=> "Mediobanca",
			"MED"	=> "Mediolanum",
			"MEL"	=> "Meliorbanca",
			"MERI"	=> "Merloni",
			"MFBI"	=> "Montefibre",
			"MNDI"	=> "Mondadori",
			"MRI"	=> "Manuli Rubber",
			"MROI"	=> "Rotondi Evoluzio",
			"MRT"	=> "Mirato Spa",
			"MS"	=> "Mediaset",
			"MTTI"	=> "Mittel",
			"MTV"	=> "Mondo Tv",
			"MZTI"	=> "Marzotto",
			"NAII"	=> "Navig Montanari",
			"NAPIn"	=> "Banco Napoli Stk N",
			"NECI"	=> "Necchi",
			"NGB"	=> "Negri Bossi",
			"NOV"	=> "Novuspharma",
			"NTV"	=> "Bca Antonveneta",
			"OLCI"	=> "Olcese",
			"OLI"	=> "Olidata Spa",
			"OLIV"	=> "Olivetti",
			"ONB"	=> "On Banca",
			"OPG"	=> "Opengate Group",
			"PAG"	=> "Pagnossin Spa",
			"PCRE"	=> "Pirelli&c Real E",
			"PCVI"	=> "Cred Valtellines",
			"PECI"	=> "Pirelli Ec",
			"PEL"	=> "Bca Erturi-lazio",
			"PELI"	=> "Perlier",
			"PGPI"	=> "Banca Bergamo",
			"PINI"	=> "Banca Intra",
			"PIRI"	=> "Pirelli",
			"PLA"	=> "Eplanet",
			"PLOI"	=> "Banca Lodi",
			"PLVI"	=> "Banca Luino",
			"PMII"	=> "Banca Milano",
			"PMS"	=> "Permasteelisa",
			"PNNI"	=> "Pininfarina",
			"POLI"	=> "Poligrafici Edt",
			"PRAI"	=> "Premafin",
			"PRFI"	=> "Parmalat",
			"PRII"	=> "Prima Industrie",
			"PRNI"	=> "Premuda",
			"PRO"	=> "Bca Profilo",
			"PRT"	=> "Esprinet",
			"PSF"	=> "Poligraf.s.faust",
			"RASI"	=> "Ras",
			"RATI"	=> "Ratti",
			"RDM"	=> "Reno De Medici",
			"RECI"	=> "Recordati",
			"REY"	=> "Reply",
			"RG"	=> "Richard-ginori",
			"RIC"	=> "Gr Cer Ricchetti",
			"RINI"	=> "Rinascente",
			"RN"	=> "Risan Napoli",
			"ROE"	=> "Roland",
			"RON"	=> "Roncadin Spa",
			"SAB"	=> "Sabaf S.p.a",
			"SAD"	=> "Sadi",
			"SAE"	=> "Saeco Group",
			"SAEI"	=> "Saes",
			"SAGI"	=> "Saiag",
			"SARIn"	=> "Bk Sardegna Stk N",
			"SCHI"	=> "Schiapparelli",
			"SDB"	=> "Savino Del Bene",
			"SGFI"	=> "Sogefi",
			"SIAI"	=> "Snia",
			"SIC"	=> "Sicc S.p.a.",
			"SIFI"	=> "Finmeccanica",
			"SIII"	=> "Sai",
			"SISI"	=> "S I S A",
			"SMII"	=> "Smi Metalli",
			"SNA"	=> "Snai Ord Spa",
			"SOL"	=> "Sol Spa",
			"SPFI"	=> "Sopaf",
			"SPG"	=> "Seat Pag.gialle",
			"SPI"	=> "San Paolo-imi",
			"SPMI"	=> "Saipem",
			"SPO"	=> "Bca Pop Spoleto",
			"SRG"	=> "Snam Rete Gas",
			"SSL"	=> "S.sportiva Lazio",
			"STAY"	=> "Stayer Group Spa",
			"STEP"	=> "Stefanel",
			"STM"	=> "",
			"TAQI"	=> "Terme Acqui",
			"TAS"	=> "Tas",
			"TCS"	=> "Tc Sistema",
			"TDIF"	=> "Tecnodiffusione",
			"TEKI"	=> "Intek Spa",
			"TFI"	=> "Trevi-fin Indust",
			"TIM"	=> "Tim",
			"TIS"	=> "Tiscali",
			"TIT"	=> "Telecom Italia",
			"TOD"	=> "Tod's",
			"TOSI"	=> "Banca Toscana",
			"TRGT"	=> "Targetti Sankey",
			"TXTS"	=> "Txt E-solutions",
			"UNPI"	=> "Unipol",
			"VEM"	=> "Vemer Elettronic",
			"VIAI"	=> "Vianini Lavori",
			"VIAIr"	=> "Vianini Industr",
			"VIT"	=> "Vitaminic",
			"VITI"	=> "Vittoria",
			"VVE"	=> "Viaggi Ventaglio",
			"ZIGI"	=> "Zignago",
			"ZUCI"	=> "Zucchi"
		);
	}
} // END OF StockSymbols_MLSE

?>
